version: '3.7'

services:
  nest_api_dev:
    tty: true
    stdin_open: true
    container_name: nest_api_dev
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9331:9330
      - 3333:3000
    environment:
      - REDIS=api_redis_my_bitcoin
      - NODE_ENV=development
      - PG_HOST=api_database_my_bitcoin
      - PG_DATABASE=nest_api
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_PASSWORD=admin
      - SECRET_JWT=139b812008b3ab0443d30b92d4f9527854d02141
      - TYPEORM_MIGRATION_FOLDER=/usr/src/app/src/database/migrations/*.ts
      - LOG_LEVEL=info
  nest_api:
    container_name: nest_api
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9330:9330
      - 3000:3000
    environment:
      - REDIS=api_redis_my_bitcoin
      - NODE_ENV=development
      - PG_HOST=api_database_my_bitcoin
      - PG_DATABASE=nest_api
      - PG_PORT=5432
      - PG_USERNAME=postgres
      - PG_PASSWORD=admin
      - SECRET_JWT=139b812008b3ab0443d30b92d4f9527854d02141
      - TYPEORM_MIGRATION_FOLDER='/usr/src/app/src/database/migrations/*.ts'
      - LOG_LEVEL=info
    command: npm run start:debug
    depends_on:
      - api_redis_my_bitcoin
      - api_database_my_bitcoin
  api_redis_my_bitcoin:
    container_name: api_redis_my_bitcoin
    image: redis:alpine3.16
    ports:
      - 16380:6379
  api_database_my_bitcoin:
    image: postgres:alpine3.16
    container_name: api_database_my_bitcoin
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest_api      
    volumes:
      - ${HOME}/docker/postgresql/api_database_my_bitcoin:/var/lib/postgresql:z
    ports:
      - "35433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api_mailer_my_bitcoin:
    image: maildev/maildev
    container_name: api_mailer_my_bitcoin
    environment:
      - MAILDEV_MAIL_DIRECTORY=/home/maildev/data
    volumes:
      - ${HOME}/docker/maildev/api_mailer_my_bitcoin:/home/maildev/data
    ports:
      - "21080:1080"
      - "21025:1025"
volumes:
  node_modules:
